# Generated by Django 5.2.1 on 2025-05-23 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_usermodel_role_alter_usermodel_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('admin', 'Admin')], default='user'),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='status',
            field=models.CharField(choices=[('inactive', 'Inactive'), ('active', 'Active')], default='active'),
        ),
    ]
