# Generated by Django 5.2.1 on 2025-05-23 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_usermodel_role_alter_usermodel_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
