# Generated by Django 5.2.1 on 2025-05-26 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_usermodel_deleted_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='usermodel',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='usermodel',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='usermodel',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='usermodel',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='usermodel',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='usermodel',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='usermodel',
            name='user_permissions',
        ),
        migrations.RemoveField(
            model_name='usermodel',
            name='username',
        ),
    ]
