# Generated by Django 5.2.1 on 2025-06-04 08:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_menu_category_menu_sub_category_menu_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu_items',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='menu_sub_category',
            name='name',
            field=models.CharField(default='default', max_length=225),
        ),
        migrations.AlterField(
            model_name='menu_category',
            name='name',
            field=models.CharField(default='default', max_length=225),
        ),
        migrations.AlterField(
            model_name='menu_items',
            name='name',
            field=models.CharField(default='default', max_length=225),
        ),
        migrations.CreateModel(
            name='Menu_add_on_items',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='default', max_length=225)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('status', models.CharField(choices=[('inactive', 'Inactive'), ('active', 'Active')], default='active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('menu_items', models.ForeignKey(db_column='menu_items_id', on_delete=django.db.models.deletion.CASCADE, related_name='menu_add_on_items', to='api.menu_items')),
            ],
        ),
    ]
