# Generated by Django 5.2.1 on 2025-06-11 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_cartitem_cart_alter_cartitem_items'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='items',
            new_name='item',
        ),
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together={('cart', 'item')},
        ),
    ]
